In [1]:
import numpy as np

In [2]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,21,35]])
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 21, 35]])

In [3]:
av = np.empty([4,3])
av

array([[1.84590514e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.12947967e-042],
       [6.58871378e-066, 6.86860696e+169, 7.92024200e+165],
       [3.76240585e+179, 2.58082395e-057, 3.44190262e+175]])

In [4]:
az = np.zeros([3,5])
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
ao = np.ones([3,5])
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
af = np.full([3,5],9)
af

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [7]:
ai = np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
ar = np.arange(1,5)
ar


array([1, 2, 3, 4])

In [9]:
al = np.linspace(1,100,20)
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [10]:
aran = np.random.random([2,3])
aran

array([[0.67086989, 0.49654162, 0.58792473],
       [0.96258547, 0.70087927, 0.72088624]])

In [11]:
aran.ndim

2

In [12]:
aran.shape

(2, 3)

In [13]:
aran.dtype

dtype('float64')

In [14]:
at = np.array(['Hola','mundo'])
at.dtype

dtype('<U5')

In [15]:
np.info(al.astype)

a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

Parameters
----------
dtype : str or dtype
    Typecode or data-type to which the array is cast.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout order of the result.
    'C' means C order, 'F' means Fortran order, 'A'
    means 'F' order if all the arrays are Fortran contiguous,
    'C' order otherwise, and 'K' means as close to the
    order the array elements appear in memory as possible.
    Default is 'K'.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'unsafe'
    for backwards compatibility.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64

In [16]:
al.astype('i')


array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [17]:
np.sort(al)


array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [18]:
aran

array([[0.67086989, 0.49654162, 0.58792473],
       [0.96258547, 0.70087927, 0.72088624]])

In [19]:
np.sort(aran,1)

array([[0.49654162, 0.58792473, 0.67086989],
       [0.70087927, 0.72088624, 0.96258547]])

In [20]:
np.sort(aran,axis=1)

array([[0.49654162, 0.58792473, 0.67086989],
       [0.70087927, 0.72088624, 0.96258547]])

In [21]:
arr = np.array([2,3,4,5,0,6,1,5,4,-3])

In [22]:
np.min(arr)
np.max(arr)
np.mean(arr)
np.median(arr)
np.absolute(arr)
np.abs(arr)
np.cumsum(arr)
np.unique(arr)
np.exp(arr)
np.prod(arr)


0

In [23]:
np.NAN

nan

In [24]:
for x in arr:
    print(x)

2
3
4
5
0
6
1
5
4
-3


In [25]:
for i in range(len(arr)):
    print(i, arr[i])

0 2
1 3
2 4
3 5
4 0
5 6
6 1
7 5
8 4
9 -3


In [26]:
for x in aran:
    for y in x:
        print(y)

0.6708698898717556
0.4965416213218451
0.5879247333823001
0.9625854718540925
0.7008792708809809
0.7208862359661876


In [27]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 21, 35]])

In [28]:
for x in a3:
    for y in x:
        for z in y:
            print(z)

TypeError: 'numpy.int64' object is not iterable

In [54]:
np.info(np.nditer)

 nditer()

nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

Efficient multi-dimensional iterator object to iterate over arrays.
To get started using this object, see the
:ref:`introductory guide to array iteration <arrays.nditer>`.

Parameters
----------
op : ndarray or sequence of array_like
    The array(s) to iterate over.

flags : sequence of str, optional
      Flags to control the behavior of the iterator.

      * ``buffered`` enables buffering when required.
      * ``c_index`` causes a C-order index to be tracked.
      * ``f_index`` causes a Fortran-order index to be tracked.
      * ``multi_index`` causes a multi-index, or a tuple of indices
        with one per iteration dimension, to be tracked.
      * ``common_dtype`` causes all the operands to be converted to
        a common data type, with copying or buffering as necessary.
      * ``copy_if_overlap`` causes the iterator to determine if read


In [55]:
for x in np.nditer(a3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
21
35


In [56]:
np.info(np.ndenumerate)

 ndenumerate(arr)

Multidimensional index iterator.

Return an iterator yielding pairs of array coordinates and values.

Parameters
----------
arr : ndarray
  Input array.

See Also
--------
ndindex, flatiter

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> for index, x in np.ndenumerate(a):
...     print(index, x)
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [57]:
for pos, x in np.ndenumerate(a3):
    print(pos, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9
(3, 0) 10
(3, 1) 11
(3, 2) 12
(4, 0) 13
(4, 1) 21
(4, 2) 35


In [58]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [67]:
np.where(a3 < 5)

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))

In [73]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 21, 35]])

In [78]:
a3[a3>1]
a3[:2]
a3[:2,1:]
a3[(a3 >1) & (a3 % 2 == 0)]


array([ 2,  4,  6,  8, 10, 12])

In [84]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr = np.concatenate((arr1, arr2), axis=1)
arr

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [86]:
arrs = np.stack((arr1, arr2), axis=1)
arr

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [89]:
arrs = np.stack((arr1, arr2), axis=0)
arrs

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [90]:
arr

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [92]:
splitted = np.array_split(arr, 3)
splitted
for s in splitted:
    print(s)

[[1 2 3 1 2 3]]
[[4 5 6 4 5 6]]
[[7 8 9 7 8 9]]


In [94]:
arr = np.array([1, 2, np.nan, 7, 4, 0])
print(arr)
sum(arr)

[ 1.  2. nan  7.  4.  0.]


nan

In [109]:
for x in arr:
    if np.isnan(x):
        x = 0

print(arr)

[0. 0. 0. 0. 0. 0.]


In [110]:


for pos in range(len(arr)):
    if not np.isnan(arr[pos]):
        arr[pos] = 0
        

print(arr)

[0. 0. 0. 0. 0. 0.]


In [111]:
lista = [x for x in arr if not np.isnan(x)]
np.array(lista)

array([0., 0., 0., 0., 0., 0.])

In [112]:
np.isnan(arr)

array([False, False, False, False, False, False])

In [115]:
copia = arr.copy()
vista = arr.view()

print('original:', arr)
print('copia:', copia)
print('vista:', vista)

arr[0] = 67

print('original:', arr)
print('copia:', copia)
print('vista:', vista)


original: [0. 0. 0. 0. 0. 0.]
copia: [0. 0. 0. 0. 0. 0.]
vista: [0. 0. 0. 0. 0. 0.]
original: [67.  0.  0.  0.  0.  0.]
copia: [0. 0. 0. 0. 0. 0.]
vista: [67.  0.  0.  0.  0.  0.]


In [116]:
arr.dtype

dtype('float64')

In [117]:
vista = arr.view(dtype = 'float32')
print('vista:', vista)

vista: [0.        3.2617188 0.        0.        0.        0.        0.
 0.        0.        0.        0.        0.       ]


In [118]:
vista = arr.view(dtype = np.int32)
print('vista:', vista)

vista: [         0 1079033856          0          0          0          0
          0          0          0          0          0          0]


In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = arr.reshape([2,3,2])
print(arr2)
arro = arr2.reshape(12)
arro

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,1,1], [2,2,2]])
print(a*b)


[[ 1  2  3]
 [ 8 10 12]]


In [38]:
a = np.array([[1,2], [4,5]])
b = np.array([[1,1], [2,2]])
print(a)

[[1 2]
 [4 5]]


In [40]:
print(np.linalg.norm(a))

6.782329983125268


In [42]:
a.T
np.linalg.det(a)

-2.9999999999999996

In [43]:
# 1x + 2y = 1
# 3x + 5y = 2


a = np.array([[1,2], [4,5]])
b = np.array([1,2])

np.linalg.solve(a,b)

array([-0.33333333,  0.66666667])

Ejercicio 1

In [70]:
import numpy as np

# Crear un array de 1 dimensión con longitud 6
array_1d = np.arange(6)

# Crear un array de 2 dimensiones con dimensiones 3 x 2
array_2d = np.arange(6).reshape(3, 2)

# Crear un array de 3 dimensiones con dimensiones 2 x 3 x 4
array_3d = np.arange(24).reshape(2, 3, 4)

array_1d, array_2d, array_3d




(array([0, 1, 2, 3, 4, 5]),
 array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

Ejercicio 2

In [79]:
def resumen_estadistico(array):
    """
    Genera un resumen estadístico básico para un array de 1 dimensión.
    Si el array tiene más de una dimensión, muestra un mensaje de alerta.
    """
    if array.ndim > 1:
        return "El array tiene más de una dimensión. Solo se admiten arrays de 1 dimensión."
    
    resumen = {
        "Media": np.mean(array),
        "Mediana": np.median(array),
        "Varianza": np.var(array),
        "Desviación Estándar": np.std(array),
        "Mínimo": np.min(array),
        "Máximo": np.max(array),
        "Primer Cuartil (Q1)": np.percentile(array, 25),
        "Segundo Cuartil (Mediana)": np.percentile(array, 50),
        "Tercer Cuartil (Q3)": np.percentile(array, 75)
    }
    return resumen

# Probar la función con un array de 1 dimensión
resumen_1d = resumen_estadistico(array_1d)

# Probar la función con un array de más de 1 dimensión
mensaje_alerta = resumen_estadistico(array_2d)

resumen_1d, mensaje_alerta


({'Media': 2.5,
  'Mediana': 2.5,
  'Varianza': 2.9166666666666665,
  'Desviación Estándar': 1.707825127659933,
  'Mínimo': 0,
  'Máximo': 5,
  'Primer Cuartil (Q1)': 1.25,
  'Segundo Cuartil (Mediana)': 2.5,
  'Tercer Cuartil (Q3)': 3.75},
 'El array tiene más de una dimensión. Solo se admiten arrays de 1 dimensión.')

Ejercicio 3 (El array proporcionado tiene 3 dimensiones con una forma de 
(4,2,3)(4,2,3), lo que significa que:

Tiene 4 bloques en la primera dimensión (nivel externo).
Cada bloque tiene 2 filas en la segunda dimensión.
Cada fila tiene 3 columnas en la tercera dimensión.)

Ejercicio 4

In [46]:
import numpy as np

# Crear un array 3x3 con valores aleatorios entre 0 y 100
array_random_3x3 = np.random.randint(0, 101, (3, 3))

# Función para crear arrays N x N con valores aleatorios entre 0 y 100
def crear_array_random(n):
    """
    Crea un array de tamaño N x N con valores aleatorios entre 0 y 100.
    
    Parámetros:
    n (int): Tamaño del array (filas y columnas).
    
    Retorna:
    np.array: Array N x N con valores aleatorios.
    """
    return np.random.randint(0, 101, (n, n))

# Probar la función para un array 5x5
array_random_5x5 = crear_array_random(5)

array_random_3x3, array_random_5x5


(array([[ 3,  1,  7],
        [ 6, 75, 80],
        [85, 66, 44]]),
 array([[88, 93, 44, 84, 44],
        [71,  7, 46, 10, 36],
        [79, 82, 77, 96, 17],
        [40, 92, 49, 93, 21],
        [10, 15, 35,  3, 52]]))

Ejercicio 5

In [47]:
def crear_array_marco(numero):
    """
    Crea un array cuadrado de tamaño N x N con un marco de 1's y el resto de 0's.
    Si se ejecuta con el número 5, devuelve:
    
    1 1 1 1 1
    1 0 0 0 1
    1 0 0 0 1
    1 0 0 0 1
    1 1 1 1 1
    
    Parámetros:
    numero (int): Tamaño del array.
    
    Retorna:
    np.array: Array con marco de 1's y centro de 0's.
    """
    # Crear un array lleno de 0's
    array = np.zeros((numero, numero), dtype=int)
    # Rellenar los bordes con 1's
    array[0, :] = 1
    array[-1, :] = 1
    array[:, 0] = 1
    array[:, -1] = 1
    return array

# Probar la función con el número 5
array_marco = crear_array_marco(5)
array_marco


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Ejercicio 6

In [48]:
import numpy as np

def detectar_dimensiones_y_faltantes(array):
    """
    Detecta las dimensiones de un array y cuenta la cantidad de datos faltantes (NaN).
    
    Parámetros:
    array (np.array): El array a analizar.
    
    Retorna:
    dict: Diccionario con las dimensiones del array y el número de datos faltantes.
    """
    dimensiones = array.ndim
    faltantes = np.isnan(array).sum()
    return {
        "Dimensiones": dimensiones,
        "Datos faltantes (NaN)": faltantes
    }

# Crear datos de ejemplo
datos_ejemplo = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

# Probar la función con los datos de ejemplo
resultado = detectar_dimensiones_y_faltantes(datos_ejemplo)
datos_ejemplo, resultado


(array([[ 1.,  2., nan],
        [ 4., nan,  6.],
        [ 7.,  8.,  9.]]),
 {'Dimensiones': 2, 'Datos faltantes (NaN)': 2})

Ejercicio 7

In [51]:
import pandas as pd

def calcular_margenes(tabla):
    """
    Calcula los márgenes de una tabla: suma por filas, columnas y el total.
    Añade estas sumas como una fila y columna extra a la tabla original.
    
    Parámetros:
    tabla (pd.DataFrame): Tabla en forma de DataFrame de Pandas.
    
    Retorna:
    pd.DataFrame: Tabla original con los márgenes calculados añadidos.
    """
    # Calcular la suma por columnas y añadirla como una nueva fila
    tabla_con_filas = tabla.copy()
    tabla_con_filas.loc['Suma Filas'] = tabla_con_filas.sum(axis=0)
    
    # Calcular la suma por filas y añadirla como una nueva columna
    tabla_con_filas['Suma Columnas'] = tabla_con_filas.sum(axis=1)
    
    return tabla_con_filas

# Crear datos de ejemplo
tabla_ejemplo = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Probar la función con la tabla de ejemplo
tabla_con_margenes = calcular_margenes(tabla_ejemplo)

print(tabla_con_margenes)



            A   B   C  Suma Columnas
0           1   4   7             12
1           2   5   8             15
2           3   6   9             18
Suma Filas  6  15  24             45


Ejercicio 8

In [80]:
import numpy as np

def calcular_coeficiente_correlacion(x, y):
    """
    Calcula el coeficiente de correlación de Pearson entre dos arrays X e Y.
    
    Parámetros:
    x (np.array): Primer array de datos.
    y (np.array): Segundo array de datos.
    
    Retorna:
    float: Coeficiente de correlación de Pearson entre X e Y.
    """
    if len(x) != len(y):
        raise ValueError("Los arrays deben tener la misma longitud.")
    
    return np.corrcoef(x, y)[0, 1]

# Datos de ejemplo
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Calcular el coeficiente de correlación
coeficiente_correlacion = calcular_coeficiente_correlacion(x, y)
coeficiente_correlacion


0.9999999999999999

In [84]:
s = pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [88]:
s = pd.Series({'math':10, 'len':7, 'art':2})
s

math    10
len      7
art      2
dtype: int64

In [85]:
print(s.size)
print(s.index)
print(s.dtype)

6
RangeIndex(start=0, stop=6, step=1)
int64


In [92]:
print(s['math'])
print(s[1])
print(s[:2])
print(s[['len','art']])

10
7
math    10
len      7
dtype: int64
len    7
art    2
dtype: int64


/tmp/ipykernel_3790/355217546.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])


In [98]:
s = pd.Series([1,2,3,4,5,6])
print(s.count())
print(s.value_counts())
print(s.value_counts(normalize=True))
print(s.describe())
print(s.sum())
print(s.cumsum())

6
1    1
2    1
3    1
4    1
5    1
6    1
Name: count, dtype: int64
1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: proportion, dtype: float64
count    6.000000
mean     3.500000
std      1.870829
min      1.000000
25%      2.250000
50%      3.500000
75%      4.750000
max      6.000000
dtype: float64
21
0     1
1     3
2     6
3    10
4    15
5    21
dtype: int64


In [99]:
st = pd.Series(['a','b','c'])
st*4

0    aaaa
1    bbbb
2    cccc
dtype: object

In [100]:
help(s.apply)

Help on method apply in module pandas.core.series:

apply(func: 'AggFuncType', convert_dtype: 'bool | lib.NoDefault' = <no_default>, args: 'tuple[Any, ...]' = (), *, by_row: "Literal[False, 'compat']" = 'compat', **kwargs) -> 'DataFrame | Series' method of pandas.core.series.Series instance
    Invoke function on values of Series.
    
    Can be ufunc (a NumPy function that applies to the entire Series)
    or a Python function that only works on single values.
    
    Parameters
    ----------
    func : function
        Python function or NumPy ufunc to apply.
    convert_dtype : bool, default True
        Try to find better dtype for elementwise function results. If
        False, leave as dtype=object. Note that the dtype is always
        preserved for some extension array dtypes, such as Categorical.
    
        .. deprecated:: 2.1.0
            ``convert_dtype`` has been deprecated. Do ``ser.astype(object).apply()``
            instead if you want ``convert_dtype=False``.
   

In [103]:
import math
import numpy as np

s.apply(math.log)
s.apply(np.sqrt)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
5    2.449490
dtype: float64

In [106]:
s.apply(lambda x: x*2+3)
sx = pd.Series(['a', 'b', 'c', np.nan, 'd'])
print(sx)

sy = sx.dropna()
print(sy)

0      a
1      b
2      c
3    NaN
4      d
dtype: object
0    a
1    b
2    c
4    d
dtype: object
