In [1]:
import numpy as np

In [2]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,21,35]])
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 21, 35]])

In [3]:
av = np.empty([4,3])
av

array([[ 3.00909377e-316,  0.00000000e+000,  3.08962726e-316],
       [ 8.29886606e-022,  6.92082230e-310,  3.09012844e-316],
       [-3.47374072e-112,  6.92082230e-310,  3.08734587e-316],
       [ 7.52250814e-223,  6.92082229e-310,  2.83882847e-316]])

In [4]:
az = np.zeros([3,5])
az

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
ao = np.ones([3,5])
ao

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
af = np.full([3,5],9)
af

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [7]:
ai = np.identity(5)
ai

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
ar = np.arange(1,5)
ar


array([1, 2, 3, 4])

In [9]:
al = np.linspace(1,100,20)
al

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [10]:
aran = np.random.random([2,3])
aran

array([[0.70732601, 0.03905107, 0.03079768],
       [0.50279429, 0.37127704, 0.79643432]])

In [11]:
aran.ndim

2

In [12]:
aran.shape

(2, 3)

In [13]:
aran.dtype

dtype('float64')

In [14]:
at = np.array(['Hola','mundo'])
at.dtype

dtype('<U5')

In [15]:
np.info(al.astype)

a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

Copy of the array, cast to a specified type.

Parameters
----------
dtype : str or dtype
    Typecode or data-type to which the array is cast.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout order of the result.
    'C' means C order, 'F' means Fortran order, 'A'
    means 'F' order if all the arrays are Fortran contiguous,
    'C' order otherwise, and 'K' means as close to the
    order the array elements appear in memory as possible.
    Default is 'K'.
casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'unsafe'
    for backwards compatibility.

      * 'no' means the data types should not be cast at all.
      * 'equiv' means only byte-order changes are allowed.
      * 'safe' means only casts which can preserve values are allowed.
      * 'same_kind' means only safe casts or casts within a kind,
        like float64

In [16]:
al.astype('i')


array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100], dtype=int32)

In [17]:
np.sort(al)


array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [18]:
aran

array([[0.70732601, 0.03905107, 0.03079768],
       [0.50279429, 0.37127704, 0.79643432]])

In [19]:
np.sort(aran,1)

array([[0.03079768, 0.03905107, 0.70732601],
       [0.37127704, 0.50279429, 0.79643432]])

In [20]:
np.sort(aran,axis=1)

array([[0.03079768, 0.03905107, 0.70732601],
       [0.37127704, 0.50279429, 0.79643432]])

In [21]:
arr = np.array([2,3,4,5,0,6,1,5,4,-3])

In [22]:
np.min(arr)
np.max(arr)
np.mean(arr)
np.median(arr)
np.absolute(arr)
np.abs(arr)
np.cumsum(arr)
np.unique(arr)
np.exp(arr)
np.prod(arr)


0

In [23]:
np.NAN

nan

In [24]:
for x in arr:
    print(x)

2
3
4
5
0
6
1
5
4
-3


In [25]:
for i in range(len(arr)):
    print(i, arr[i])

0 2
1 3
2 4
3 5
4 0
5 6
6 1
7 5
8 4
9 -3


In [26]:
for x in aran:
    for y in x:
        print(y)

0.7073260066176629
0.03905106698383942
0.030797680338658928
0.5027942938119725
0.37127703615625285
0.7964343206318288


In [27]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 21, 35]])

In [28]:
for x in a3:
    for y in x:
        for z in y:
            print(z)

TypeError: 'numpy.int64' object is not iterable

In [ ]:
np.info(np.nditer)

In [ ]:
for x in np.nditer(a3):
    print(x)

In [ ]:
np.info(np.ndenumerate)

In [ ]:
for pos, x in np.ndenumerate(a3):
    print(pos, x)

In [58]:
np.info(np.where)

 where()

where(condition, [x, y], /)

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples

In [67]:
np.where(a3 < 5)

(array([0, 0, 0, 1]), array([0, 1, 2, 0]))

In [73]:
a3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 21, 35]])

In [78]:
a3[a3>1]
a3[:2]
a3[:2,1:]
a3[(a3 >1) & (a3 % 2 == 0)]


array([ 2,  4,  6,  8, 10, 12])

In [84]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr = np.concatenate((arr1, arr2), axis=1)
arr

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [86]:
arrs = np.stack((arr1, arr2), axis=1)
arr

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [89]:
arrs = np.stack((arr1, arr2), axis=0)
arrs

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [90]:
arr

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [92]:
splitted = np.array_split(arr, 3)
splitted
for s in splitted:
    print(s)

[[1 2 3 1 2 3]]
[[4 5 6 4 5 6]]
[[7 8 9 7 8 9]]


In [94]:
arr = np.array([1, 2, np.nan, 7, 4, 0])
print(arr)
sum(arr)

[ 1.  2. nan  7.  4.  0.]


nan

In [109]:
for x in arr:
    if np.isnan(x):
        x = 0

print(arr)

[0. 0. 0. 0. 0. 0.]


In [110]:


for pos in range(len(arr)):
    if not np.isnan(arr[pos]):
        arr[pos] = 0
        

print(arr)

[0. 0. 0. 0. 0. 0.]


In [111]:
lista = [x for x in arr if not np.isnan(x)]
np.array(lista)

array([0., 0., 0., 0., 0., 0.])

In [112]:
np.isnan(arr)

array([False, False, False, False, False, False])

In [115]:
copia = arr.copy()
vista = arr.view()

print('original:', arr)
print('copia:', copia)
print('vista:', vista)

arr[0] = 67

print('original:', arr)
print('copia:', copia)
print('vista:', vista)


original: [0. 0. 0. 0. 0. 0.]
copia: [0. 0. 0. 0. 0. 0.]
vista: [0. 0. 0. 0. 0. 0.]
original: [67.  0.  0.  0.  0.  0.]
copia: [0. 0. 0. 0. 0. 0.]
vista: [67.  0.  0.  0.  0.  0.]


In [116]:
arr.dtype

dtype('float64')

In [117]:
vista = arr.view(dtype = 'float32')
print('vista:', vista)

vista: [0.        3.2617188 0.        0.        0.        0.        0.
 0.        0.        0.        0.        0.       ]


In [118]:
vista = arr.view(dtype = np.int32)
print('vista:', vista)

vista: [         0 1079033856          0          0          0          0
          0          0          0          0          0          0]


In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2 = arr.reshape([2,3,2])
print(arr2)
arro = arr2.reshape(12)
arro

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,1,1], [2,2,2]])
print(a*b)


[[ 1  2  3]
 [ 8 10 12]]


In [38]:
a = np.array([[1,2], [4,5]])
b = np.array([[1,1], [2,2]])
print(a)

[[1 2]
 [4 5]]


In [40]:
print(np.linalg.norm(a))

6.782329983125268


In [42]:
a.T
np.linalg.det(a)

-2.9999999999999996

In [43]:
# 1x + 2y = 1
# 3x + 5y = 2


a = np.array([[1,2], [4,5]])
b = np.array([1,2])

np.linalg.solve(a,b)

array([-0.33333333,  0.66666667])

Ejercicio 1

In [70]:
import numpy as np

# Crear un array de 1 dimensión con longitud 6
array_1d = np.arange(6)

# Crear un array de 2 dimensiones con dimensiones 3 x 2
array_2d = np.arange(6).reshape(3, 2)

# Crear un array de 3 dimensiones con dimensiones 2 x 3 x 4
array_3d = np.arange(24).reshape(2, 3, 4)

array_1d, array_2d, array_3d




(array([0, 1, 2, 3, 4, 5]),
 array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

Ejercicio 2

In [79]:
def resumen_estadistico(array):
    """
    Genera un resumen estadístico básico para un array de 1 dimensión.
    Si el array tiene más de una dimensión, muestra un mensaje de alerta.
    """
    if array.ndim > 1:
        return "El array tiene más de una dimensión. Solo se admiten arrays de 1 dimensión."
    
    resumen = {
        "Media": np.mean(array),
        "Mediana": np.median(array),
        "Varianza": np.var(array),
        "Desviación Estándar": np.std(array),
        "Mínimo": np.min(array),
        "Máximo": np.max(array),
        "Primer Cuartil (Q1)": np.percentile(array, 25),
        "Segundo Cuartil (Mediana)": np.percentile(array, 50),
        "Tercer Cuartil (Q3)": np.percentile(array, 75)
    }
    return resumen

# Probar la función con un array de 1 dimensión
resumen_1d = resumen_estadistico(array_1d)

# Probar la función con un array de más de 1 dimensión
mensaje_alerta = resumen_estadistico(array_2d)

resumen_1d, mensaje_alerta


({'Media': 2.5,
  'Mediana': 2.5,
  'Varianza': 2.9166666666666665,
  'Desviación Estándar': 1.707825127659933,
  'Mínimo': 0,
  'Máximo': 5,
  'Primer Cuartil (Q1)': 1.25,
  'Segundo Cuartil (Mediana)': 2.5,
  'Tercer Cuartil (Q3)': 3.75},
 'El array tiene más de una dimensión. Solo se admiten arrays de 1 dimensión.')

Ejercicio 3 (El array proporcionado tiene 3 dimensiones con una forma de 
(4,2,3)(4,2,3), lo que significa que:

Tiene 4 bloques en la primera dimensión (nivel externo).
Cada bloque tiene 2 filas en la segunda dimensión.
Cada fila tiene 3 columnas en la tercera dimensión.)

Ejercicio 4

In [46]:
import numpy as np

# Crear un array 3x3 con valores aleatorios entre 0 y 100
array_random_3x3 = np.random.randint(0, 101, (3, 3))

# Función para crear arrays N x N con valores aleatorios entre 0 y 100
def crear_array_random(n):
    """
    Crea un array de tamaño N x N con valores aleatorios entre 0 y 100.
    
    Parámetros:
    n (int): Tamaño del array (filas y columnas).
    
    Retorna:
    np.array: Array N x N con valores aleatorios.
    """
    return np.random.randint(0, 101, (n, n))

# Probar la función para un array 5x5
array_random_5x5 = crear_array_random(5)

array_random_3x3, array_random_5x5


(array([[ 3,  1,  7],
        [ 6, 75, 80],
        [85, 66, 44]]),
 array([[88, 93, 44, 84, 44],
        [71,  7, 46, 10, 36],
        [79, 82, 77, 96, 17],
        [40, 92, 49, 93, 21],
        [10, 15, 35,  3, 52]]))

Ejercicio 5

In [47]:
def crear_array_marco(numero):
    """
    Crea un array cuadrado de tamaño N x N con un marco de 1's y el resto de 0's.
    Si se ejecuta con el número 5, devuelve:
    
    1 1 1 1 1
    1 0 0 0 1
    1 0 0 0 1
    1 0 0 0 1
    1 1 1 1 1
    
    Parámetros:
    numero (int): Tamaño del array.
    
    Retorna:
    np.array: Array con marco de 1's y centro de 0's.
    """
    # Crear un array lleno de 0's
    array = np.zeros((numero, numero), dtype=int)
    # Rellenar los bordes con 1's
    array[0, :] = 1
    array[-1, :] = 1
    array[:, 0] = 1
    array[:, -1] = 1
    return array

# Probar la función con el número 5
array_marco = crear_array_marco(5)
array_marco


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Ejercicio 6

In [48]:
import numpy as np

def detectar_dimensiones_y_faltantes(array):
    """
    Detecta las dimensiones de un array y cuenta la cantidad de datos faltantes (NaN).
    
    Parámetros:
    array (np.array): El array a analizar.
    
    Retorna:
    dict: Diccionario con las dimensiones del array y el número de datos faltantes.
    """
    dimensiones = array.ndim
    faltantes = np.isnan(array).sum()
    return {
        "Dimensiones": dimensiones,
        "Datos faltantes (NaN)": faltantes
    }

# Crear datos de ejemplo
datos_ejemplo = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

# Probar la función con los datos de ejemplo
resultado = detectar_dimensiones_y_faltantes(datos_ejemplo)
datos_ejemplo, resultado


(array([[ 1.,  2., nan],
        [ 4., nan,  6.],
        [ 7.,  8.,  9.]]),
 {'Dimensiones': 2, 'Datos faltantes (NaN)': 2})

Ejercicio 7

In [51]:
import pandas as pd

def calcular_margenes(tabla):
    """
    Calcula los márgenes de una tabla: suma por filas, columnas y el total.
    Añade estas sumas como una fila y columna extra a la tabla original.
    
    Parámetros:
    tabla (pd.DataFrame): Tabla en forma de DataFrame de Pandas.
    
    Retorna:
    pd.DataFrame: Tabla original con los márgenes calculados añadidos.
    """
    # Calcular la suma por columnas y añadirla como una nueva fila
    tabla_con_filas = tabla.copy()
    tabla_con_filas.loc['Suma Filas'] = tabla_con_filas.sum(axis=0)
    
    # Calcular la suma por filas y añadirla como una nueva columna
    tabla_con_filas['Suma Columnas'] = tabla_con_filas.sum(axis=1)
    
    return tabla_con_filas

# Crear datos de ejemplo
tabla_ejemplo = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Probar la función con la tabla de ejemplo
tabla_con_margenes = calcular_margenes(tabla_ejemplo)

print(tabla_con_margenes)



            A   B   C  Suma Columnas
0           1   4   7             12
1           2   5   8             15
2           3   6   9             18
Suma Filas  6  15  24             45


Ejercicio 8

In [80]:
import numpy as np

def calcular_coeficiente_correlacion(x, y):
    """
    Calcula el coeficiente de correlación de Pearson entre dos arrays X e Y.
    
    Parámetros:
    x (np.array): Primer array de datos.
    y (np.array): Segundo array de datos.
    
    Retorna:
    float: Coeficiente de correlación de Pearson entre X e Y.
    """
    if len(x) != len(y):
        raise ValueError("Los arrays deben tener la misma longitud.")
    
    return np.corrcoef(x, y)[0, 1]

# Datos de ejemplo
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Calcular el coeficiente de correlación
coeficiente_correlacion = calcular_coeficiente_correlacion(x, y)
coeficiente_correlacion


0.9999999999999999

In [84]:
s = pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [88]:
s = pd.Series({'math':10, 'len':7, 'art':2})
s

math    10
len      7
art      2
dtype: int64

In [85]:
print(s.size)
print(s.index)
print(s.dtype)

6
RangeIndex(start=0, stop=6, step=1)
int64


In [92]:
print(s['math'])
print(s[1])
print(s[:2])
print(s[['len','art']])

10
7
math    10
len      7
dtype: int64
len    7
art    2
dtype: int64


/tmp/ipykernel_3790/355217546.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])


In [98]:
s = pd.Series([1,2,3,4,5,6])
print(s.count())
print(s.value_counts())
print(s.value_counts(normalize=True))
print(s.describe())
print(s.sum())
print(s.cumsum())

6
1    1
2    1
3    1
4    1
5    1
6    1
Name: count, dtype: int64
1    0.166667
2    0.166667
3    0.166667
4    0.166667
5    0.166667
6    0.166667
Name: proportion, dtype: float64
count    6.000000
mean     3.500000
std      1.870829
min      1.000000
25%      2.250000
50%      3.500000
75%      4.750000
max      6.000000
dtype: float64
21
0     1
1     3
2     6
3    10
4    15
5    21
dtype: int64


In [99]:
st = pd.Series(['a','b','c'])
st*4

0    aaaa
1    bbbb
2    cccc
dtype: object

In [100]:
help(s.apply)

Help on method apply in module pandas.core.series:

apply(func: 'AggFuncType', convert_dtype: 'bool | lib.NoDefault' = <no_default>, args: 'tuple[Any, ...]' = (), *, by_row: "Literal[False, 'compat']" = 'compat', **kwargs) -> 'DataFrame | Series' method of pandas.core.series.Series instance
    Invoke function on values of Series.
    
    Can be ufunc (a NumPy function that applies to the entire Series)
    or a Python function that only works on single values.
    
    Parameters
    ----------
    func : function
        Python function or NumPy ufunc to apply.
    convert_dtype : bool, default True
        Try to find better dtype for elementwise function results. If
        False, leave as dtype=object. Note that the dtype is always
        preserved for some extension array dtypes, such as Categorical.
    
        .. deprecated:: 2.1.0
            ``convert_dtype`` has been deprecated. Do ``ser.astype(object).apply()``
            instead if you want ``convert_dtype=False``.
   

In [103]:
import math
import numpy as np

s.apply(math.log)
s.apply(np.sqrt)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
5    2.449490
dtype: float64

In [106]:
s.apply(lambda x: x*2+3)
sx = pd.Series(['a', 'b', 'c', np.nan, 'd'])
print(sx)

sy = sx.dropna()
print(sy)

0      a
1      b
2      c
3    NaN
4      d
dtype: object
0    a
1    b
2    c
4    d
dtype: object


In [34]:
import pandas as pd

s = pd.Series([1,2,3,4,5,6])

mask = s > 2
print(mask)



0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool


In [35]:
sx = pd.Series(['a', 'a', None, 'c', np.nan, 'd'])
print(sx)

sy = sx.dropna()
print(sy)

0       a
1       a
2    None
3       c
4     NaN
5       d
dtype: object
0    a
1    a
3    c
5    d
dtype: object


In [36]:
import pandas as pd

# Serie de datos originales
serie = pd.Series([100, 200, 'python', 300.12, 400])
print("Serie de datos originales:")
print(serie)
print("Tipo original:", serie.dtype)

# Convertir la serie a tipo numérico (convirtiendo valores no numéricos en NaN)
serie_numerica = pd.to_numeric(serie, errors='coerce')

# Mostrar la serie convertida
print("\nCambio a numérico:")
print(serie_numerica)
print("Tipo:", serie_numerica.dtype)


Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Tipo original: object

Cambio a numérico:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64
Tipo: float64


In [37]:
import pandas as pd

# Serie de listas de colores
serie_listas = pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])

# Mostrar la serie original
print("Serie original de listas:")
print(serie_listas)

# Convertir la serie de listas en una serie plana
serie_plana = serie_listas.explode()

# Mostrar la serie transformada
print("\nUna serie:")
print(serie_plana)
print("dtype:", serie_plana.dtype)


Serie original de listas:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

Una serie:
0       Red
0     Green
0     White
1       Red
1     Black
2    Yellow
dtype: object
dtype: object


In [38]:
import pandas as pd

# Serie de datos original
serie = pd.Series([100, 200, 'python', 300.12, 400])

# Mostrar la serie original
print("Serie de datos originales:")
print(serie)
print("dtype:", serie.dtype)

# Datos a agregar
nuevos_datos = pd.Series([500, 'php'])

# Concatenar la serie original con los nuevos datos
serie_actualizada = pd.concat([serie, nuevos_datos], ignore_index=True)

# Mostrar la serie después de agregar datos
print("\nSerie de datos después de agregar algunos datos:")
print(serie_actualizada)
print("dtype:", serie_actualizada.dtype)


Serie de datos originales:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
dtype: object

Serie de datos después de agregar algunos datos:
0       100
1       200
2    python
3    300.12
4       400
5       500
6       php
dtype: object
dtype: object


In [39]:
import pandas as pd

# Crear la serie de datos original
serie = pd.Series(range(11))  # Crea valores de 0 a 10

# Mostrar la serie original
print("Serie de datos originales:")
print(serie)
print("tipo:", serie.dtype)

# Aplicar una condición para obtener un subconjunto (valores menores o iguales a 5)
subserie = serie[serie <= 5]

# Mostrar la subserie resultante
print("\nSubconjunto de la serie de datos anterior:")
print(subserie)
print("tipo:", subserie.dtype)


Serie de datos originales:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
tipo: int64

Subconjunto de la serie de datos anterior:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
tipo: int64


In [40]:
import pandas as pd

# Crear la serie de datos original con índice personalizado
serie = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])

# Mostrar la serie original
print("Serie de datos originales:")
print(serie)
print("tipo:", serie.dtype)

# Cambiar el orden del índice de la serie
nuevo_orden = ['B', 'A', 'C', 'D', 'E']
serie_reordenada = serie.reindex(nuevo_orden)

# Mostrar la serie después de cambiar el orden del índice
print("\nSerie de datos después de cambiar el orden del índice:")
print(serie_reordenada)
print("tipo:", serie_reordenada.dtype)


Serie de datos originales:
A    1
B    2
C    3
D    4
E    5
dtype: int64
tipo: int64

Serie de datos después de cambiar el orden del índice:
B    2
A    1
C    3
D    4
E    5
dtype: int64
tipo: int64


In [41]:
import pandas as pd

# Crear las series de datos originales
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

# Mostrar las series originales
print("Serie original:")
print("sr1:")
print(sr1)
print("sr2:")
print(sr2)

# Obtener los elementos de sr1 que no están en sr2
sr1_unicos = sr1[~sr1.isin(sr2)]

# Mostrar los elementos únicos de sr1
print("\nElementos de sr1 no presentes en sr2:")
print(sr1_unicos)
print("tipo:", sr1_unicos.dtype)


Serie original:
sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64
sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Elementos de sr1 no presentes en sr2:
0    1
2    3
4    5
dtype: int64
tipo: int64


In [42]:
import pandas as pd
import numpy as np

# Crear una serie de ejemplo con valores repetidos
serie = pd.Series(np.random.randint(0, 10, size=40))  # Genera 40 números entre 0 y 9

# Mostrar la serie original
print("Serie original:")
print(serie)

# Calcular la frecuencia de cada valor único
frecuencia = serie.value_counts()

# Mostrar los conteos de frecuencia
print("\nFrecuencia de cada valor único de dicha serie:")
print(frecuencia)
print("tipo:", frecuencia.dtype)


Serie original:
0     0
1     3
2     2
3     1
4     8
5     3
6     3
7     5
8     1
9     8
10    1
11    9
12    6
13    3
14    0
15    4
16    2
17    1
18    2
19    1
20    5
21    8
22    9
23    6
24    5
25    1
26    6
27    0
28    3
29    3
30    8
31    7
32    3
33    0
34    4
35    2
36    3
37    1
38    7
39    6
dtype: int64

Frecuencia de cada valor único de dicha serie:
3    8
1    7
0    4
2    4
8    4
6    4
5    3
9    2
4    2
7    2
Name: count, dtype: int64
tipo: int64


In [43]:
import pandas as pd

# Crear una serie de ejemplo
serie = pd.Series([3, 1, 1, 3, 2, 3, 1, 2, 2, 3, 1, 3, 2, 3, 3])

# Mostrar la serie original
print("Serie original:")
print(serie)

# Obtener las frecuencias de cada valor
frecuencias = serie.value_counts()

# Mostrar las frecuencias
print("\nFrecuencias principales:")
print(frecuencias)
print("tipo:", frecuencias.dtype)

# Obtener el valor más frecuente
valor_mas_frecuente = frecuencias.idxmax()

# Reemplazar todos los valores excepto el más frecuente con 'Otro'
serie_reemplazada = serie.apply(lambda x: x if x == valor_mas_frecuente else 'Otro')

# Mostrar la serie después de reemplazar
print("\nSerie después de reemplazar valores no frecuentes con 'Otro':")
print(serie_reemplazada)
print("dtype:", serie_reemplazada.dtype)


Serie original:
0     3
1     1
2     1
3     3
4     2
5     3
6     1
7     2
8     2
9     3
10    1
11    3
12    2
13    3
14    3
dtype: int64

Frecuencias principales:
3    7
1    4
2    4
Name: count, dtype: int64
tipo: int64

Serie después de reemplazar valores no frecuentes con 'Otro':
0        3
1     Otro
2     Otro
3        3
4     Otro
5        3
6     Otro
7     Otro
8     Otro
9        3
10    Otro
11       3
12    Otro
13       3
14       3
dtype: object
dtype: object


In [44]:
import pandas as pd

# Definir la serie original
serie1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Definir la serie con elementos a buscar
serie2 = pd.Series([1, 3, 5, 7, 10])

# Mostrar las series originales
print("Serie original:")
print(serie1)
print("tipo:", serie1.dtype)

print("\nElementos a buscar en la serie original:")
print(serie2)
print("tipo:", serie2.dtype)

# Obtener las posiciones de los elementos de serie2 en serie1
posiciones = serie1[serie1.isin(serie2)].index.tolist()

# Mostrar las posiciones encontradas
print("\nPosiciones de los elementos de la serie 2 en la serie 1:")
print(posiciones)


Serie original:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
tipo: int64

Elementos a buscar en la serie original:
0     1
1     3
2     5
3     7
4    10
dtype: int64
tipo: int64

Posiciones de los elementos de la serie 2 en la serie 1:
[0, 2, 4, 6, 9]


In [45]:
import pandas as pd

# Crear la serie de ejemplo
serie = pd.Series(['php', 'python', 'java', 'c#'])

# Mostrar la serie original
print("Serie original:")
print(serie)

# Función para convertir el primer y último carácter en mayúscula
def capitalizar_extremos(palabra):
    if len(palabra) > 1:
        return palabra[0].upper() + palabra[1:-1] + palabra[-1].upper()
    else:
        return palabra.upper()

# Aplicar la función a cada elemento de la serie
serie_modificada = serie.apply(capitalizar_extremos)

# Mostrar la serie transformada
print("\nPrimer y último carácter de cada palabra en mayúscula:")
print(serie_modificada)
print("dtype:", serie_modificada.dtype)


Serie original:
0       php
1    python
2      java
3        c#
dtype: object

Primer y último carácter de cada palabra en mayúscula:
0       PhP
1    PythoN
2      JavA
3        C#
dtype: object
dtype: object


In [46]:
import pandas as pd

# Crear la serie de ejemplo
serie = pd.Series([1, 3, 5, 8, 10, 11, 15])

# Mostrar la serie original
print("Serie original:")
print(serie)
print("tipo:", serie.dtype)

# Calcular la primera diferencia (diferencias consecutivas)
primera_diferencia = serie.diff()

# Calcular la segunda diferencia (diferencia de diferencias)
segunda_diferencia = primera_diferencia.diff()

# Mostrar los resultados
print("\nDiferencia entre números consecutivos de la serie:")
print(primera_diferencia.tolist())

print("\nDiferencia de diferencias entre números consecutivos de la serie:")
print(segunda_diferencia.tolist())


Serie original:
0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64
tipo: int64

Diferencia entre números consecutivos de la serie:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]

Diferencia de diferencias entre números consecutivos de la serie:
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Configuración de conexión (ajusta según tu base de datos)
db_tipo = 'postgresql'  # Ejemplo: 'mysql', 'sqlite', 'mssql'
usuario = 'tu_usuario'
contraseña = 'tu_contraseña'
host = 'localhost'  # o la dirección IP del servidor
puerto = '5432'  # Puerto por defecto de PostgreSQL
db_nombre = 'datafundamentals'

# Crear la cadena de conexión
conexion_str = f'{db_tipo}://{usuario}:{contraseña}@{host}:{puerto}/{db_nombre}'

# Crear el motor de conexión
engine = create_engine(conexion_str)

# Cargar la tabla 'pagos' en un DataFrame de Pandas
try:
    df_pagos = pd.read_sql('SELECT * FROM pagos', engine)
    print("Datos cargados correctamente:")
    print(df_pagos.head())  # Mostrar los primeros registros
except Exception as e:
    print("Error al cargar los datos:", e)


In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Configuración de conexión a la base de datos
db_tipo = 'postgresql'  # Cambiar a 'mysql+mysqlconnector' para MySQL
usuario = 'tu_usuario'
contraseña = 'tu_contraseña'
host = 'localhost'  # Cambia por la dirección IP del servidor si es necesario
puerto = '5432'  # Puerto por defecto de PostgreSQL
db_nombre = 'datafundamentals'

# Crear la cadena de conexión
db_url = f'{db_tipo}://{usuario}:{contraseña}@{host}:{puerto}/{db_nombre}'

# Crear motor de conexión
engine = create_engine(db_url)

# Crear un DataFrame de ejemplo
df_pagos = pd.DataFrame({
    'id_pago': [1, 2, 3],
    'monto': [100.50, 200.75, 150.00],
    'fecha': ['2023-01-01', '2023-02-01', '2023-03-01']
})

# Guardar el DataFrame en la base de datos como una nueva tabla llamada 'pagos_nueva'
df_pagos.to_sql('pagos_nueva', engine, if_exists='replace', index=False)

print("Datos guardados en la tabla 'pagos_nueva' correctamente.")

# Consultar las tablas existentes en la base de datos
query_list_tables = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'"

# Leer la lista de tablas en un DataFrame de Pandas
df_tablas = pd.read_sql(query_list_tables, engine)

# Mostrar las tablas de la base de datos
print("\nTablas existentes en la base de datos:")
print(df_tablas)

# Comprobar si la nueva tabla existe
if 'pagos_nueva' in df_tablas['table_name'].values:
    print("\n¡La tabla 'pagos_nueva' existe en la base de datos!")
else:
    print("\nLa tabla 'pagos_nueva' NO fue encontrada en la base de datos.")


In [1]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'id': [1, 2, 3, 4, 5],
    'name': ['Ana', 'Luis', 'Carlos', 'Beatriz', 'Pedro'],
    'amount': [300, 450, 500, 200, 600]
}

df = pd.DataFrame(data)

# Mostrar el DataFrame original
print("DataFrame original:")
print(df)

# Filtrar filas donde 'amount' sea mayor que 400
df_filtrado = df[df['amount'] > 400]

# Mostrar el DataFrame filtrado
print("\nFilas donde 'amount' es mayor que 400:")
print(df_filtrado)


DataFrame original:
   id     name  amount
0   1      Ana     300
1   2     Luis     450
2   3   Carlos     500
3   4  Beatriz     200
4   5    Pedro     600

Filas donde 'amount' es mayor que 400:
   id    name  amount
1   2    Luis     450
2   3  Carlos     500
4   5   Pedro     600


In [2]:
import pandas as pd

# Crear un DataFrame de ejemplo con varias columnas
data = {
    'checknumber': ['CHK001', 'CHK002', 'CHK003', 'CHK004'],
    'paymentdate': ['2023-01-10', '2023-02-15', '2023-03-20', '2023-04-25'],
    'amount': [500, 300, 450, 600],
    'customer': ['Ana', 'Luis', 'Carlos', 'Beatriz']
}

df = pd.DataFrame(data)

# Mostrar el DataFrame original
print("DataFrame original:")
print(df)

# Seleccionar solo las columnas "checknumber" y "paymentdate"
df_seleccionado = df[['checknumber', 'paymentdate']]

# Mostrar el DataFrame con las columnas seleccionadas
print("\nDataFrame con columnas seleccionadas:")
print(df_seleccionado)


DataFrame original:
  checknumber paymentdate  amount customer
0      CHK001  2023-01-10     500      Ana
1      CHK002  2023-02-15     300     Luis
2      CHK003  2023-03-20     450   Carlos
3      CHK004  2023-04-25     600  Beatriz

DataFrame con columnas seleccionadas:
  checknumber paymentdate
0      CHK001  2023-01-10
1      CHK002  2023-02-15
2      CHK003  2023-03-20
3      CHK004  2023-04-25


In [ ]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'Region': ['Norte', 'Norte', 'Sur', 'Sur', 'Este', 'Este'],
    'Ciudad': ['Madrid', 'Barcelona', 'Sevilla', 'Granada', 'Valencia', 'Alicante'],
    'Ventas': [1000, 1200, 800, 750, 950, 1100]
}

df = pd.DataFrame(data)

# Definir un MultiIndex basado en las columnas 'Region' y 'Ciudad'
df.set_index(['Region', 'Ciudad'], inplace=True)

# Mostrar el DataFrame con el MultiIndex
print("DataFrame con MultiIndex:")
print(df)

# Acceder a datos específicos con MultiIndex
print("\nAcceder a datos de la ciudad 'Madrid' en la región 'Norte':")
print(df.loc[('Norte', 'Madrid')])

# Segmentar el DataFrame por nivel de índice (seleccionar todas las ciudades de una región)
print("\nDatos de la región 'Sur':")
print(df.loc['Sur'])

# Acceder a todas las ciudades de la región 'Norte' con el método xs
print("\nDatos de la región 'Norte' usando xs:")
print(df.xs('Norte', level='Region'))


In [3]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'ID': [1, 2, 3, 4, 5],
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Beatriz', 'Pedro'],
    'Edad': [25, 30, 22, 28, 35]
}

df = pd.DataFrame(data)

# Mostrar el DataFrame original
print("DataFrame original:")
print(df)

# Seleccionar las primeras tres filas usando iloc
df_tres_filas = df.iloc[:3]

# Mostrar las primeras tres filas seleccionadas
print("\nPrimeras tres filas del DataFrame:")
print(df_tres_filas)


DataFrame original:
   ID   Nombre  Edad
0   1      Ana    25
1   2     Luis    30
2   3   Carlos    22
3   4  Beatriz    28
4   5    Pedro    35

Primeras tres filas del DataFrame:
   ID  Nombre  Edad
0   1     Ana    25
1   2    Luis    30
2   3  Carlos    22


In [4]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'Nombre': ['Ana', 'Luis', 'Carlos', 'Beatriz', 'Pedro'],
    'Edad': [25, 30, 22, 28, 35],
    'Salario': [50000, 60000, 40000, 55000, 65000]
}

df = pd.DataFrame(data)

# Mostrar el DataFrame original
print("DataFrame original:")
print(df)

# Aplicar condición en dos columnas: seleccionar personas con Edad > 25 y Salario > 50000
df_filtrado = df.loc[(df['Edad'] > 25) & (df['Salario'] > 50000)]

# Mostrar las filas filtradas
print("\nFilas donde la Edad > 25 y el Salario > 50000:")
print(df_filtrado)


DataFrame original:
    Nombre  Edad  Salario
0      Ana    25    50000
1     Luis    30    60000
2   Carlos    22    40000
3  Beatriz    28    55000
4    Pedro    35    65000

Filas donde la Edad > 25 y el Salario > 50000:
    Nombre  Edad  Salario
1     Luis    30    60000
3  Beatriz    28    55000
4    Pedro    35    65000


In [5]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'ID': [1, 2, 3, 4, 5],
    'Cliente': ['Ana', 'Luis', 'Carlos', 'Beatriz', 'Pedro'],
    'Amount': [300, 450, 500, 200, 600]
}

df = pd.DataFrame(data)

# Mostrar el DataFrame original
print("DataFrame original:")
print(df)

# Condición: Cambiar 'Amount' a 999 donde 'Amount' sea mayor que 400
df.loc[df['Amount'] > 400, 'Amount'] = 999

# Mostrar el DataFrame después de la modificación
print("\nDataFrame después de modificar la columna 'Amount':")
print(df)


DataFrame original:
   ID  Cliente  Amount
0   1      Ana     300
1   2     Luis     450
2   3   Carlos     500
3   4  Beatriz     200
4   5    Pedro     600

DataFrame después de modificar la columna 'Amount':
   ID  Cliente  Amount
0   1      Ana     300
1   2     Luis     999
2   3   Carlos     999
3   4  Beatriz     200
4   5    Pedro     999


In [6]:
import pandas as pd

# Crear un DataFrame de ejemplo
data = {
    'Producto': ['Manzana', 'Banana', 'Cereza', 'Durazno', 'Fresa'],
    'Cantidad': [10, 20, 15, 25, 30],
    'Precio': [1.5, 0.8, 2.0, 2.5, 1.8]
}

df = pd.DataFrame(data, index=['A', 'B', 'C', 'D', 'E'])

# Mostrar el DataFrame original
print("DataFrame original:")
print(df)

# Dividir el DataFrame seleccionando filas 'A' a 'C' y columnas 'Producto' y 'Cantidad'
df_subconjunto = df.loc['A':'C', ['Producto', 'Cantidad']]

# Mostrar el subconjunto del DataFrame
print("\nSubconjunto del DataFrame con filas 'A' a 'C' y columnas 'Producto' y 'Cantidad':")
print(df_subconjunto)

# Otra segmentación seleccionando filas específicas y columnas específicas
df_segmento = df.loc[['B', 'D'], ['Producto', 'Precio']]

# Mostrar otra segmentación
print("\nSegmento del DataFrame con filas 'B' y 'D' y columnas 'Producto' y 'Precio':")
print(df_segmento)


DataFrame original:
  Producto  Cantidad  Precio
A  Manzana        10     1.5
B   Banana        20     0.8
C   Cereza        15     2.0
D  Durazno        25     2.5
E    Fresa        30     1.8

Subconjunto del DataFrame con filas 'A' a 'C' y columnas 'Producto' y 'Cantidad':
  Producto  Cantidad
A  Manzana        10
B   Banana        20
C   Cereza        15

Segmento del DataFrame con filas 'B' y 'D' y columnas 'Producto' y 'Precio':
  Producto  Precio
B   Banana     0.8
D  Durazno     2.5


In [7]:
import pandas as pd

# Crear un DataFrame con MultiIndex
arrays = [
    ['Norte', 'Norte', 'Sur', 'Sur', 'Este', 'Este'],
    ['Madrid', 'Barcelona', 'Sevilla', 'Granada', 'Valencia', 'Alicante']
]
index = pd.MultiIndex.from_tuples(list(zip(*arrays)), names=['Region', 'Ciudad'])

data = {
    'Poblacion': [3200000, 1600000, 700000, 500000, 800000, 330000],
    'PIB': [30000, 28000, 22000, 21000, 25000, 23000]
}

df = pd.DataFrame(data, index=index)

# Mostrar el DataFrame con MultiIndex
print("DataFrame con MultiIndex:")
print(df)

# 1. Seleccionar datos de una región específica (ej. 'Norte')
print("\nSegmentación por región 'Norte':")
df_norte = df.loc['Norte']
print(df_norte)

# 2. Seleccionar datos de una ciudad específica dentro de una región
print("\nSegmentación por 'Norte' y ciudad 'Madrid':")
df_madrid = df.loc[('Norte', 'Madrid')]
print(df_madrid)

# 3. Seleccionar datos de múltiples ciudades dentro de una región
print("\nSegmentación por múltiples ciudades en 'Sur':")
df_sur = df.loc[('Sur', ['Sevilla', 'Granada']), :]
print(df_sur)

# 4. Seleccionar una columna específica con multi-índice
print("\nSegmentación para obtener la columna 'PIB' de la región 'Este':")
df_este_pib = df.loc['Este', 'PIB']
print(df_este_pib)

# 5. Seleccionar datos con múltiples niveles de índices
print("\nSegmentación específica: Región 'Norte' y todas las columnas:")
df_norte_todas_columnas = df.loc[('Norte', slice(None)), :]
print(df_norte_todas_columnas)


DataFrame con MultiIndex:
                  Poblacion    PIB
Region Ciudad                     
Norte  Madrid       3200000  30000
       Barcelona    1600000  28000
Sur    Sevilla       700000  22000
       Granada       500000  21000
Este   Valencia      800000  25000
       Alicante      330000  23000

Segmentación por región 'Norte':
           Poblacion    PIB
Ciudad                     
Madrid       3200000  30000
Barcelona    1600000  28000

Segmentación por 'Norte' y ciudad 'Madrid':
Poblacion    3200000
PIB            30000
Name: (Norte, Madrid), dtype: int64

Segmentación por múltiples ciudades en 'Sur':
                Poblacion    PIB
Region Ciudad                   
Sur    Sevilla     700000  22000
       Granada     500000  21000

Segmentación para obtener la columna 'PIB' de la región 'Este':
Ciudad
Valencia    25000
Alicante    23000
Name: PIB, dtype: int64

Segmentación específica: Región 'Norte' y todas las columnas:
                  Poblacion    PIB
Region Ciudad   

In [4]:
import pandas as pd
import numpy as np


# Ejercicio 1: Concatenación de DataFrames por Filas
df1 = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Marta'],
    'Grado': ['10°', '10°', '10°'],
    'Promedio': [8.5, 7.8, 9.0]
})

df2 = pd.DataFrame({
    'Nombre': ['Carlos', 'Lucía'],
    'Grado': ['11°', '11°'],
    'Promedio': [8.2, 9.3]
})

df_combinado_filas = pd.concat([df1, df2], ignore_index=True)

print("Concatenación por filas (Ejercicio 1):")
print(df_combinado_filas)


Concatenación por filas (Ejercicio 1):
   Nombre Grado  Promedio
0     Ana   10°       8.5
1    Luis   10°       7.8
2   Marta   10°       9.0
3  Carlos   11°       8.2
4   Lucía   11°       9.3


In [5]:
# Ejercicio 2: Concatenación de DataFrames por Columnas
df_productos = pd.DataFrame({
    'ID_Producto': [1, 2, 3],
    'Nombre': ['Manzanas', 'Plátanos', 'Naranjas']
})

df_precios = pd.DataFrame({
    'Precio': [1.2, 0.8, 1.5],
    'Stock': [100, 200, 150]
})

df_combinado_columnas = pd.concat([df_productos, df_precios], axis=1)
print("\nConcatenación por columnas (Ejercicio 2):")
print(df_combinado_columnas)


Concatenación por columnas (Ejercicio 2):
   ID_Producto    Nombre  Precio  Stock
0            1  Manzanas     1.2    100
1            2  Plátanos     0.8    200
2            3  Naranjas     1.5    150


In [6]:
# Ejercicio 3: Uso de pd.cut para Agrupar Datos
df_ventas = pd.DataFrame({
    'ID_Venta': [101, 102, 103, 104, 105],
    'Monto': [200, 450, 300, 150, 500]
})

df_ventas['Categoría'] = pd.cut(df_ventas['Monto'], bins=[0, 200, 400, float('inf')], labels=['Bajo', 'Medio', 'Alto'])
print("\nAgrupación con pd.cut (Ejercicio 3):")
print(df_ventas)


Agrupación con pd.cut (Ejercicio 3):
   ID_Venta  Monto Categoría
0       101    200      Bajo
1       102    450      Alto
2       103    300     Medio
3       104    150      Bajo
4       105    500      Alto


In [7]:
# Ejercicio 4: Concatenación y Operaciones Mixtas
ventas_enero = pd.DataFrame({
    'ID_Venta': [1, 2, 3],
    'Producto': ['A', 'B', 'C'],
    'Monto': [500, 300, 450]
})

ventas_febrero = pd.DataFrame({
    'ID_Venta': [4, 5, 6],
    'Producto': ['A', 'B', 'D'],
    'Monto': [700, 200, 600]
})

ventas_totales = pd.concat([ventas_enero, ventas_febrero], ignore_index=True)
ventas_totales['Categoría'] = pd.cut(ventas_totales['Monto'], bins=[0, 300, 600, float('inf')], labels=['Bajo', 'Medio', 'Alto'])
monto_total = ventas_totales['Monto'].sum()
print("\nConcatenación y Categorías (Ejercicio 4):")
print(ventas_totales)
print(f"Total de Ventas: {monto_total}")


Concatenación y Categorías (Ejercicio 4):
   ID_Venta Producto  Monto Categoría
0         1        A    500     Medio
1         2        B    300      Bajo
2         3        C    450     Medio
3         4        A    700      Alto
4         5        B    200      Bajo
5         6        D    600     Medio
Total de Ventas: 2750


In [8]:
# Ejercicio 5: Concatenación con Índices Desajustados
df_a = pd.DataFrame({'A': [1, 2]}, index=[0, 1])
df_b = pd.DataFrame({'B': [3, 4]}, index=[2, 3])

concatenado_desajustado = pd.concat([df_a, df_b], axis=1)
concatenado_alineado = pd.concat([df_a, df_b], axis=1, ignore_index=True)
print("\nConcatenación con índices desajustados (Ejercicio 5):")
print(concatenado_desajustado)


Concatenación con índices desajustados (Ejercicio 5):
     A    B
0  1.0  NaN
1  2.0  NaN
2  NaN  3.0
3  NaN  4.0


In [9]:
# Ejercicio 6: Crear un DataFrame y usar pd.cut
np.random.seed(42)
edades = np.random.randint(18, 65, size=20)
df_edades = pd.DataFrame({'Edad': edades})
df_edades['Grupo_Edad'] = pd.cut(df_edades['Edad'], bins=[18, 25, 45, 65], labels=['Joven', 'Adulto', 'Mayor'])
print("\nEdades categorizadas (Ejercicio 6):")
print(df_edades)


Edades categorizadas (Ejercicio 6):
    Edad Grupo_Edad
0     56      Mayor
1     46      Mayor
2     32     Adulto
3     60      Mayor
4     25      Joven
5     38     Adulto
6     56      Mayor
7     36     Adulto
8     40     Adulto
9     28     Adulto
10    28     Adulto
11    41     Adulto
12    53      Mayor
13    57      Mayor
14    41     Adulto
15    20      Joven
16    39     Adulto
17    19      Joven
18    41     Adulto
19    61      Mayor


In [10]:
# Ejercicio 7: Concatenación con Claves
ventas_norte = pd.DataFrame({'Producto': ['A', 'B'], 'Monto': [300, 400]})
ventas_sur = pd.DataFrame({'Producto': ['C', 'D'], 'Monto': [200, 500]})

ventas_por_region = pd.concat([ventas_norte, ventas_sur], keys=['Norte', 'Sur'])
print("\nVentas por región (Ejercicio 7):")
print(ventas_por_region)


Ventas por región (Ejercicio 7):
        Producto  Monto
Norte 0        A    300
      1        B    400
Sur   0        C    200
      1        D    500


In [13]:
import pandas as pd
import numpy as np

# Ventas de enero y febrero
ventas_totales = pd.DataFrame({
    'ID_Venta': [1, 2, 3, 4, 5, 6],
    'Producto': ['A', 'B', 'C', 'A', 'B', 'D'],
    'Monto': [500, 300, 450, 700, 200, 600]
})

# Generación de edades aleatorias
np.random.seed(42)
edades = np.random.randint(18, 65, size=6)  # Ajustado al número de filas de ventas_totales
df_edades = pd.DataFrame({'Edad': edades})

# Combinación de datos
datos_totales = pd.concat([ventas_totales, df_edades], axis=1)

# Agregar categorías para las edades y los montos
datos_totales['Grupo_Edad'] = pd.cut(
    datos_totales['Edad'],
    bins=[18, 25, 45, 65],
    labels=['Joven', 'Adulto', 'Mayor']
)

datos_totales['Rango_Ventas'] = pd.cut(
    datos_totales['Monto'],
    bins=[0, 300, 600, float('inf')],
    labels=['Bajo', 'Medio', 'Alto']
)

# Filtrar adultos con ventas "Medio" o "Alto"
filtro_adultos_ventas_medias_altas = datos_totales[
    (datos_totales['Grupo_Edad'] == 'Adulto') & 
    (datos_totales['Rango_Ventas'].isin(['Medio', 'Alto']))
]

# Mostrar resultados
print("Datos combinados del Reto Final:")
print(datos_totales)

print("\nFiltro de Adultos con Ventas Medias o Altas:")
print(filtro_adultos_ventas_medias_altas)

Datos combinados del Reto Final:
   ID_Venta Producto  Monto  Edad Grupo_Edad Rango_Ventas
0         1        A    500    56      Mayor        Medio
1         2        B    300    46      Mayor         Bajo
2         3        C    450    32     Adulto        Medio
3         4        A    700    60      Mayor         Alto
4         5        B    200    25      Joven         Bajo
5         6        D    600    38     Adulto        Medio

Filtro de Adultos con Ventas Medias o Altas:
   ID_Venta Producto  Monto  Edad Grupo_Edad Rango_Ventas
2         3        C    450    32     Adulto        Medio
5         6        D    600    38     Adulto        Medio


In [5]:
import os

# Ruta relativa del archivo
file_path = 'Users/aurelio.sosa.netmind/Pandas/titanic.csv'

# Obtener la ruta absoluta
absolute_path = os.path.abspath(file_path)
print("Ruta absoluta del archivo:", absolute_path)

Ruta absoluta del archivo: /mnt/batch/tasks/shared/LS_root/mounts/clusters/aurelio-parra/code/Users/aurelio.sosa.netmind/Users/aurelio.sosa.netmind/Pandas/titanic.csv


In [ ]:
import pandas as pd

# Cargar el dataset del Titanic
file_path = r'Users/aurelio.sosa.netmind/Pandas/titanic.csv'
titanic_data = pd.read_csv(file_path)

# Visualizar las primeras filas del dataset para entender su estructura
titanic_data.head()

In [11]:
import pandas as pd

# Ruta absoluta del archivo en tu entorno de Azure
file_path = '/mnt/batch/tasks/shared/LS_root/mounts/clusters/aurelio-parra/code/Users/aurelio.sosa.netmind/Users/aurelio.sosa.netmind/Pandas/titanic.csv'

# Intentar cargar el archivo
try:
    titanic_data = pd.read_csv(file_path)
    print("Archivo cargado correctamente. Primeras filas:")
    print(titanic_data.head())
except FileNotFoundError as e:
    print(f"Error: {e}")
    print("Asegúrate de que el archivo esté disponible en la ruta especificada.")


Error: [Errno 2] No such file or directory: '/mnt/batch/tasks/shared/LS_root/mounts/clusters/aurelio-parra/code/Users/aurelio.sosa.netmind/Users/aurelio.sosa.netmind/Pandas/titanic.csv'
Asegúrate de que el archivo esté disponible en la ruta especificada.
